# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Razvan Marescu
email: razvan@marescu.net
tagline: Software Engineer from Vancouver, Canada
description: Independent software engineer from Vancouver, Canada
url: "https://razvan.marescu.net"
timezone: America/Vancouver

# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#author-information
author:
  name: Razvan Marescu
  github: rmarescu
  linkedin: rmarescu
  stackshare: rmarescu
  strava: rmarescu
  twitter: rmarescu

sass:
  load_paths:
    - node_modules/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - bin/
  - assets/images/icons/
  - CNAME
  - README.md
  - package.json
  - postcss.config.js
  - yarn.lock
