name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
      - uses: ruby/setup-ruby@v1.120.0
        with:
          bundler-cache: true

      - name: Set up Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.12.0

      - name: Set up Yarn
        run: |
          yarn install --pure-lockfile
          
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
